// Entry point. All real logic lives in lib.rs (`img2typtex_lib::run`) so the
// app can also be exercised from integration tests / other binaries if ever
// needed - this split is the standard convention generated by `create-tauri-app`.
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

fn main() {
    img2typtex_lib::run();
}
